## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file main.sagetex.sage
from sage.all_cmdline import *   # import sage library
## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
